//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string NumberAccount { get; set; }
        public int UserID { get; set; }
        public double Amount { get; set; }
        public int Period { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public double Percet { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual Users Users { get; set; }
    }
}
